version: '3.9'
services:
  gama-db:
    env_file:
      - apps/backend/.env
    image: postgres:16.0
    container_name: digitalkin-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  dbdata:
